apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotify-clone
  labels:
    app: spotify-clone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spotify-clone
  template:
    metadata:
      labels:
        app: spotify-clone
    spec:
      containers:
      - name: spotify-clone
        image: ghcr.io/GITHUB_USERNAME/spotify-clone:latest
        # Replace GITHUB_USERNAME with your actual GitHub username when deploying
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
        env:
        - name: NODE_ENV
          value: "production"